

name: Browserstack_Mobile_Safari

on:
  workflow_dispatch
#  schedule:
#    - cron: '0 6 * * *'
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run LoginTest on LambdaTest
      run: mvn clean test -Dtest=TestSuite -Denvironment=browserstack_safari_mobile -Dwebdriver.timeouts.implicitlywait=9000 -Dserenity.timeout=9000 -Dsurefire.rerunFailingTestsCount=1 -Dmaven.test.failure.ignore=true
    - name: Generate Report
      if: always()
      run: mvn serenity:aggregate -Dmaven.test.failure.ignore=true
    - name: Upload Summary Test Report
      if: always()
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TestReport_Summary
        path: target/site/serenity/serenity-summary.html
    - name: Upload Full Test Report
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TestReport_Full
        path: target/site/serenity