name: Run All Tests

on:
  workflow_dispatch
#  schedule:
#    - cron: '0 6 * * *'
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  mobile_ios_safari:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run LoginTest on LambdaTest
        run: mvn clean test -Dtest=TestSuite -Denvironment=lambdatest_safari_mobile -Dwebdriver.timeouts.implicitlywait=9000 -Dserenity.timeout=9000 -Dsurefire.rerunFailingTestsCount=1 -Dmaven.test.failure.ignore=true
      - name: Generate Report
        if: always()
        run: mvn serenity:aggregate -Dmaven.test.failure.ignore=true
      - name: Upload Summary Test Report
        if: always()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: TestReport_Summary
          path: target/site/serenity/serenity-summary.html

  desktop_safari:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run LoginTest on LambdaTest
        run: mvn clean test -Dtest=TestSuite -Denvironment=safari_web -Dwebdriver.timeouts.implicitlywait=9000 -Dserenity.timeout=9000 -Dsurefire.rerunFailingTestsCount=1 -Dmaven.test.failure.ignore=true
      - name: Generate Report
        if: always()
        run: mvn serenity:aggregate -Dmaven.test.failure.ignore=true
      - name: Upload Summary Test Report
        if: always()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: TestReport_Summary
          path: target/site/serenity/serenity-summary.html

  desktop_chrome:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run LoginTest on LambdaTest
        run: mvn clean test -Dtest=TestSuite -Denvironment=chrome_web -Dwebdriver.timeouts.implicitlywait=9000 -Dserenity.timeout=9000 -Dsurefire.rerunFailingTestsCount=1 -Dmaven.test.failure.ignore=true
      - name: Generate Report
        if: always()
        run: mvn serenity:aggregate -Dmaven.test.failure.ignore=true
      - name: Upload Summary Test Report
        if: always()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: TestReport_Summary
          path: target/site/serenity/serenity-summary.html

  mobile_android_chrome:
    runs-on: macos-latest
    needs: [mobile_ios_safari, desktop_safari, desktop_chrome]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run LoginTest on LambdaTest
        run: mvn clean test -Dtest=TestSuite -Denvironment=lambdatest_chrome_mobile -Dwebdriver.timeouts.implicitlywait=9000 -Dserenity.timeout=9000 -Dsurefire.rerunFailingTestsCount=1 -Dmaven.test.failure.ignore=true
      - name: Generate Report
        if: always()
        run: mvn serenity:aggregate -Dmaven.test.failure.ignore=true
      - name: Upload Summary Test Report
        if: always()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: TestReport_Summary
          path: target/site/serenity/serenity-summary.html